CREATE DATABASE IF NOT EXISTS reports;
USE reports;

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  source VARCHAR(100) NOT NULL,
  title VARCHAR(500) NOT NULL,
  url VARCHAR(750) NOT NULL UNIQUE,
  body MEDIUMTEXT NULL,
  fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
